name: Clear cache

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: '45 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clear cache
      run: |
        curl -s https://purge.jsdelivr.net/gh/FenghenHome/adguard-home-filters@gh-pages/filters.txt
        curl -s https://purge.jsdelivr.net/gh/FenghenHome/adguard-home-filters@gh-pages/regex.txt
